### ISSUE TITLE
Thumbnails with finite=true works like finite=false

### ISSUE THREAD

**Issue by oceandrama** [igordanchenko/yet-another-react-lightbox#205] opened 2023-11-16 10:19 UTC
### Describe the bug

Thumbnail carousel looks infinite even with finite=false in settings

### Expected behavior

Thumbnails end with the main carousel
Also I think the thumbnail shouldn't dissapear if it's already preloaded

### How to reproduce

[Link to sandbox](https://codesandbox.io/p/sandbox/yet-another-react-lightbox-examples-forked-lqsjwn?file=%2Fsrc%2Fexamples%2FBasicExample.tsx&initialpath=%2Fexamples%2Fbasic&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clor2b76600093j6gbqjqoj05%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clor2b76600043j6gv3dkfg2z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clor2b76600063j6gws7hkviv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clor2b76600083j6g2g8gf685%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clor2b76600043j6gv3dkfg2z%2522%253A%257B%2522id%2522%253A%2522clor2b76600043j6gv3dkfg2z%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clor2hqo900033j6f5kqmphex%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fexamples%252FInlinePlugin.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clor2hqo900033j6f5kqmphex%2522%257D%252C%2522clor2b76600083j6g2g8gf685%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clor2b76600073j6g9uf9igqy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252Fplugins%252Finline%2522%257D%255D%252C%2522id%2522%253A%2522clor2b76600083j6g2g8gf685%2522%252C%2522activeTabId%2522%253A%2522clor2b76600073j6g9uf9igqy%2522%257D%252C%2522clor2b76600063j6gws7hkviv%2522%253A%257B%2522id%2522%253A%2522clor2b76600063j6gws7hkviv%2522%252C%2522activeTabId%2522%253A%2522clp10q7bd03pm3j6gn3x2ix58%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clp10q7bd03pm3j6gn3x2ix58%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Screenshots / Logs

![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/23439079/f285b60e-5001-4fd2-a987-2d61781f1e2a)

**Comment by igordanchenko** [comment] 2023-11-16 14:05
> Thumbnail carousel looks infinite even with finite=false in settings

This is actually the intended design. In "finite" mode there are no thumbnails to the left of the first slide and to the right of the last slide, and the first and the last visible thumbnails have a vignette effect (which you can disable with `thumbnails={{ vignette: false }}`). 

Please see the below screenshots demonstrating the difference between `finite: true` and `finite: false`.

`carousel={{ finite: true }}`

<img width="650" alt="Screenshot 2023-11-16 at 8 40 42 AM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/3ccdfeef-ef22-4afb-a82f-2d9710502f18">

`carousel={{ finite: false }}`

<img width="649" alt="Screenshot 2023-11-16 at 8 40 19 AM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/36998dc8-844c-4afe-a409-36e5ef8142d6">

You can probably adjust the number of preloaded thumbnails based on the viewport size to achieve the desired behavior.

```jsx
const [open, setOpen] = React.useState(false);
const [viewport, setViewport] = React.useState<number>();

React.useEffect(() => {
  const updateViewport = () => {
    setViewport(window.innerWidth);
  };

  updateViewport();

  window.addEventListener("resize", updateViewport);
  return () => window.removeEventListener("resize", updateViewport);
}, []);

return (
  <>
    <Lightbox
      open={open}
      close={() => setOpen(false)}
      slides={slides}
      plugins={[Thumbnails, Video, Zoom]}
      carousel={{
        finite: true,
        preload: viewport ? Math.min(Math.floor((viewport - 170) / 292), 3) : undefined,
      }}
      thumbnails={{ vignette: false }}
    />

    {/* ... */}
  </>
);
```

Does this address your concern?

> Also I think the thumbnail shouldn't dissapear if it's already preloaded

IMO, this behavior would look odd on large viewports.

**Comment by oceandrama** [comment] 2023-11-16 14:14
But in 

> In "finite" mode there are no thumbnails to the left of the first slide and to the right of the last slide

But on my screenshot there are thumbnails to the right of the last slide. This is the last image and below I can see the last and the first thumbnail
![image](https://github.com/igordanchenko/yet-another-react-lightbox/assets/23439079/6c7e0890-5890-4f78-9194-c9ee2da92e6e)

**Comment by igordanchenko** [comment] 2023-11-16 14:28
Can you provide reproducible example? You can use the following sandbox as a template.

https://codesandbox.io/p/sandbox/yet-another-react-lightbox-205-xf4w77

**Comment by igordanchenko** [comment] 2023-11-18 18:15
@oceandrama any chance you can share a reproducible example? I'm not seeing any issues with the sandbox you provided in the description.

The first slide:

<img width="671" alt="Screenshot 2023-11-18 at 10 10 44 AM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/09e3428c-4b0a-4388-8e66-588a82de8483">

The last slide:

<img width="670" alt="Screenshot 2023-11-18 at 10 11 11 AM" src="https://github.com/igordanchenko/yet-another-react-lightbox/assets/64441155/fd9cdb88-6a49-4689-8651-97f8eac2badf">

**Comment by oceandrama** [comment] 2023-11-20 13:46
Hmm, now it works well. That's strange. Sorry for misleading.
My primary goal was to make thumbnails scrollable for quick navigation between images (and I tried different combinations of options that lead to this bug). I can preload all images and add scroll using css, but because of placeholders it doesn't work well. Is it possible to implement this feature?

**Comment by igordanchenko** [comment] 2023-11-20 19:01
Thank you for the update. Please see the following discussion re: swipeable thumbnails - https://github.com/igordanchenko/yet-another-react-lightbox/discussions/193

Can you also describe the UX you want to achieve with swipeable thumbnails?

**Comment by oceandrama** [comment] 2023-11-24 09:02
When there are a lot of images, a few dozens, user want to quick navigate between them. Current thumnails implementation allow only to skip the next image, so if you need to go to the end you need to click and wait too many times

**Comment by igordanchenko** [comment] 2023-11-28 00:28
I'm closing this ticket since it sounds like this bug report was created erroneously.

**Closed by igordanchenko** 2023-11-28 00:28 UTC
Labels: bug
