### ISSUE TITLE
Glitchy transition on iOS Safari

### ISSUE THREAD

**Issue by jamiemill** [igordanchenko/yet-another-react-lightbox#73] opened 2023-02-17 11:24 UTC
### Describe the bug

The transition between images is glitchy on mobile safari on iOS.

When swiping, the next image flashes up in the centre then jumps to its correct position off-screen to slide in, making the transition feel janky.

It's most noticeable when swiping, but something also flashes when I tap the next/previous buttons, although it's not so prominent.

### Expected behavior

I expect when swiping or pressing 'next' the old image to slide away and the new image to slide in smoothly with no flashes of content.

### How to reproduce

Load the "Basic example" from this page on mobile safari and then swipe through: https://yet-another-react-lightbox.com/examples/basic

### Screenshots / Logs

See this screen recording on iOS 16.0 - note that the second or third swipe it becomes more prominent.

https://user-images.githubusercontent.com/66421/219638034-f636feb7-2231-4e72-b33c-1ac20798f722.mov

**Comment by igordanchenko** [comment] 2023-02-17 13:02
Hi Jamie,

Thank you for the detailed report. As crazy as it may sound, but have you tried restarting your browser? ([force quit and reopen](https://support.apple.com/guide/iphone/quit-and-reopen-an-app-iph83bfec492/ios)) 

I've seen this glitch in the past but have never been able to reproduce it reliably, and restarting the browser always cured the glitch.

**Comment by jamiemill** [comment] 2023-02-17 13:04
Writing this made me realise my iOS was a few updates behind, so I installed the update (which restarted the whole phone of course) and now the glitch is gone!

So I guess either a version update or a restart of the phone or browser solved it.

**Comment by igordanchenko** [comment] 2023-02-17 13:38
Yeah, this sporadic glitch has been driving me crazy for a long time (though I haven't seen it on my iOS devices for quite some time now). This library uses FLIP + WAAPI animation technique to animate slide swipes, and I'd really prefer to keep it this way rather than going back to CSS animation.

At this point, I have two theories about the root cause of this glitch:

1) Some pesky bug in my code that randomly causes this glitch in iOS Safari.
2) Some strange WebKit bug in iOS Safari that randomly manifests itself (dunno, maybe memory leak related since browser restart makes it go away).

I hope it's the latter and that it was fixed in one of the recent Safari versions since I haven't seen this glitch in a while.

Please let me know if you see this glitch again in the latest Safari version.

**Comment by jamiemill** [comment] 2023-02-17 13:44
OK, thanks for this great info. I'll comment if I notice it again.

**Comment by igordanchenko** [comment] 2023-03-01 15:36
I'll go ahead and close this ticket in the absence of additional reports.

**Closed by igordanchenko** 2023-03-01 15:36 UTC
Labels: bug
